import os
import re
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional

# Import custom module classes and functions
from src.optimization_engine import NewsvendorOptimizer
from src.ai_copilot import AICopilotEngine
from src.demand_forecasting import predict_item_demand

app = FastAPI(title="ChefEngine AI Ops Backend")

# Initialize Engine & Optimizer
optimizer = NewsvendorOptimizer(rmse_error=5.507)
GROQ_KEY = os.getenv("GROQ_API_KEY", "")
copilot = AICopilotEngine(api_key=GROQ_KEY, model_name="llama-3.3-70b-versatile")

# --- REQUEST SCHEMAS ---
class OptimizationRequest(BaseModel):
    item_id: str = "ITEM001"
    item_name: str
    selling_price: float
    ingredient_cost: float
    available_stock: int
    predicted_demand: Optional[float] = None
    day_of_week: int = 5
    event: int = 1
    promotion: int = 0
    temperature: float = 24.0

class CopilotQueryRequest(BaseModel):
    query: str
    item_name: str
    predicted_demand: float
    available_stock: int


# --- ENDPOINTS ---

@app.get("/")
def read_root():
    return {"status": "ChefEngine AI Backend is Live"}


@app.post("/predict-and-optimize")
def predict_and_optimize(req: OptimizationRequest):
    try:
        # 1. Determine demand forecast (manual override vs ML model prediction)
        if req.predicted_demand is not None and req.predicted_demand > 0:
            pred_demand = float(req.predicted_demand)
        else:
            pred_demand = float(predict_item_demand(
                item_name=req.item_name,
                day_of_week=req.day_of_week,
                event=req.event,
                promotion=req.promotion,
                temperature=req.temperature
            ))
            
        # 2. Run Newsvendor Optimization using calculate_optimal_prep
        opt_res = optimizer.calculate_optimal_prep(
            predicted_demand=pred_demand,
            selling_price=req.selling_price,
            ingredient_cost=req.ingredient_cost,
            available_stock=req.available_stock
        )
        
        # 3. Generate AI Copilot Brief
        explanation = copilot.generate_recommendation_explanation(
            item_name=req.item_name,
            context_data=req.dict(),
            opt_data=opt_res
        )
        
        return {
            "status": "success",
            "calculated_demand": round(float(pred_demand), 1),
            "optimization_details": opt_res,
            "ai_explanation": explanation
        }

    except Exception as e:
        print(f"❌ Error during optimization: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/copilot/query")
def copilot_query(req: CopilotQueryRequest):
    try:
        opt_data = {
            "item_name": req.item_name,
            "predicted_demand": req.predicted_demand,
            "final_recommended_prep": req.available_stock
        }
        
        response_text = copilot.answer_scenario_query(
            query=req.query,
            opt_data=opt_data
        )
        
        # Strip out any unexpected HTML block tags generated by the LLM
        cleaned_text = re.sub(r'</?div[^>]*>', '', response_text)
        
        return {"status": "success", "response": cleaned_text}
        
    except Exception as e:
        print(f"❌ Error in Copilot Query: {e}")
        raise HTTPException(status_code=500, detail=str(e))